"""Cyberwave Robot Format - Universal robot description schema and format converters.

This package provides a unified schema for representing robotic assets and tools
for converting between different robot description formats (URDF, MJCF, SDF, etc.).
"""

from cyberwave_robot_format.schema import (
    Actuator,
    ActuatorType,
    Collision,
    CollisionConfig,
    CollisionExclude,
    CollisionGroup,
    CollisionPair,
    CommonSchema,
    Contact,
    ContactSurface,
    Geometry,
    GeometryType,
    Inertia,
    Joint,
    JointDynamics,
    JointLimits,
    JointType,
    Link,
    Material,
    Metadata,
    Physics,
    PhysicsSolver,
    Pose,
    Quaternion,
    Scene,
    Sensor,
    Vector3,
    Visual,
)
from cyberwave_robot_format.urdf import URDFParser, URDFExporter, export_urdf_zip, export_urdf_scene_xml
from cyberwave_robot_format.mjcf import MJCFParser, MJCFExporter, export_mujoco_zip, export_mujoco_scene_xml
from cyberwave_robot_format.schema_export import export_universal_schema_json

__version__ = "0.1.0"
__all__ = [
    "CommonSchema",
    "Link",
    "Joint",
    "Visual",
    "Collision",
    "CollisionConfig",
    "CollisionExclude",
    "CollisionGroup",
    "CollisionPair",
    "Geometry",
    "Material",
    "Pose",
    "Vector3",
    "Quaternion",
    "Inertia",
    "JointType",
    "GeometryType",
    "JointLimits",
    "JointDynamics",
    "Actuator",
    "ActuatorType",
    "Sensor",
    "Contact",
    "ContactSurface",
    "Physics",
    "PhysicsSolver",
    "Scene",
    "Metadata",
    "URDFParser",
    "URDFExporter",
    "MJCFParser",
    "MJCFExporter",
    "export_mujoco_zip",
    "export_mujoco_scene_xml",
    "export_urdf_zip",
    "export_urdf_scene_xml",
    "export_universal_schema_json",
]
